print = ("  digite um numero:  ")
N1 = leia( )
print = ("  digite um numero:  ")
N2 = leia( )
print = (" digite outro numero:  ")
N3 = leia( )
result = (N1*N2*N3)
print = ("  seu resultado e:  " + result)
